# Generated by Django 5.0.1 on 2024-01-06 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('tender_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('aceptance_date', models.DateField()),
                ('cancelation_date', models.DateField()),
                ('payment_terms', models.CharField(max_length=255)),
                ('net_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('oc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('oc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('oc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.orders')),
            ],
        ),
    ]
