# Generated by Django 5.0.1 on 2024-01-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_orders_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='aceptance_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cancelation_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='net_total',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='tender_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='type',
        ),
    ]
