# Generated by Django 5.0.1 on 2024-01-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_rename_city_buyer_buyer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code_category',
        ),
    ]
